### ISSUE TITLE
Not sure how I pushed a new branch?

### ISSUE THREAD

**Issue by yoyothesheep** [learn-co-students/python-lists-lab-data-science-pilot#8]
<img width="1191" alt="screen shot 2018-03-15 at 10 25 05 pm" src="https://user-images.githubusercontent.com/33908481/37500437-e1e4a5aa-289f-11e8-8b32-fb47b1e42072.png">
<img width="1160" alt="screen shot 2018-03-15 at 10 25 23 pm" src="https://user-images.githubusercontent.com/33908481/37500438-e2f27382-289f-11e8-8214-01f25611d3d5.png">

**Comment by yoyothesheep** [comment]
Maybe I did a combination of accidental back button (scroll back) and reload? Not sure what race condition of mouse actions caused this.

**Comment by talum** [comment]
@yoyothesheep This is expected behavior. That's actually branch on your fork.
